name: Build

on: [push, pull_request]

jobs:
  buildUbuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        cd Linux
        make all
    - uses: actions/upload-artifact@v4
      with:
        name: P372-linux
        path: P372/Linux/libp372.so

  buildOSX:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        cd Linux
        make all

  buildWindows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build Solution
      run: |
        cd P372/Win32/P372
        msbuild /p:Configuration=Release /p:Platform="x64" P372.sln
    - uses: actions/upload-artifact@v4
      with:
        name: P372-windows
        path: P372\Win32\P372\x64\Release\P372_x64.dll
